trigger:
- main

pool: laptop

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    env:
      PATH: 'C:\terraform;$(PATH)'
    displayName: 'Build Job'
    steps:
    - powershell: |
        terraform.exe --version
      displayName: 'Check Terraform Version'


# - stage: WSL
#   displayName: 'WSL Test'
#   jobs:
#   - job: WSLJob
#     displayName: 'WSL Job'
#     steps:
#     - script: |
#         wsl ps aux
#         wsl pwd
#         wsl ls -sail
#       displayName: 'Run WSL commands'
