trigger:
- main

pool: laptop

variables:
  - name: client_secret
    value: $(client_secret)
  - name: location
    value: $(location)
  - name: subscription_id
    value: $(subscription_id)
  - name: tenant_id
    value: $(tenant_id)

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - powershell: |
        terraform.exe --version
        terraform init
        terraform plan -out=tfplan
      env:
        PATH: 'C:\terraform;$(PATH)'
        TF_VAR_client_secret: $(client_secret)
        TF_VAR_location: $(location)
        TF_VAR_subscription_id: $(subscription_id)
        TF_VAR_tenant_id: $(tenant_id)
      displayName: 'Check Terraform Version'


# - stage: WSL
#   displayName: 'WSL Test'
#   jobs:
#   - job: WSLJob
#     displayName: 'WSL Job'
#     steps:
#     - script: |
#         wsl ps aux
#         wsl pwd
#         wsl ls -sail
#       displayName: 'Run WSL commands'
