trigger:
- main

pool:
  name: laptop

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'terraform'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az account show
    - script: |
        az --version
      displayName: 'Check Azure CLI version'
    - script: |
        echo "Restoring project dependencies..."
      displayName: 'Restore dependencies'

    - script: |
        echo "Running unit tests..."
      displayName: 'Run unit tests'

- stage: WSL
  displayName: 'WSL Test'
  jobs:
  - job: WSLJob
    displayName: 'WSL Job'
    steps:
    - script: |
        wsl ps aux
        wsl pwd
        wsl ls -sail
      displayName: 'Run WSL commands'
