trigger:
- main

pool: laptop

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: |
        echo "Restoring project dependencies..."
      displayName: 'Restore dependencies'
    - script: |
        echo "Running unit tests..."
      displayName: 'Run unit tests'    
- stage: WSL
  displayName: 'wsl test'
  jobs:
  - job: WSLJob
    displayName: 'WSLJob'
    steps:
    - script: |
        wsl ps aux
        wsl pwd
        wsl ls -sail
