name: Terraform deploy Log Analytics

trigger:
  - main

pool: laptop

variables:
  azureServiceConnection: 'terra'  

stages:
  - stage: Plan
    displayName: 'Terraform Plan'
    jobs:
      - job: TerraformPlan
        displayName: 'Terraform Plan'
        steps:
          # Step 1: Initialize and Plan Terraform
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)  # The service connection defined in your pipeline
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                echo "Setting up Azure authentication using the service principal credentials from the service connection"
                echo "Terraform init..."
                terraform init
                echo "Terrform plan..."
                terraform plan
            displayName: 'Terraform init and plan'
          
          # Step 2: Deploy
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)  # The service connection defined in your pipeline
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                echo "Terraform apply"
                terraform apply -auto-approve
            displayName: 'Terraform apply'
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)  # The service connection defined in your pipeline
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                echo "Terraform apply"
                terraform destroy -auto-approve
            displayName: 'Terraform destroy'